version: 2
updates:
  # main branch
  - package-ecosystem: maven
    directory: "/"
    target-branch: main
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
    groups:
      minor:
        update-types:
          - minor
      patch:
        update-types:
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
    groups:
      actions:
        patterns:
          - "*"

  # 3.x branch
  - package-ecosystem: maven
    directory: "/"
    target-branch: "3.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "io.micrometer:*"
      - dependency-name: "io.vertx:*"
        versions: [">=5.0.0"]
      - dependency-name: "com.fasterxml.jackson.core:*"
        versions: [">=2.21.0"]
    groups:
      minor:
        update-types:
          - minor
      patch:
        update-types:
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "3.x"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
    groups:
      actions:
        patterns:
          - "*"
