name: Publish the website
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - uses: actions/setup-java@v4
        name: Set up Java 17
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version-file: "pyproject.toml"
      - name: Tools setup
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
      - name: Build local artifacts
        run: ./mvnw -s .build/maven-ci-settings.xml -B install -DskipTests
      - name: Render docs and publish
        run: .build/render-documentation.sh